apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: backend

  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.0
        
        ports:
        - name: liveness-port
          containerPort: 6379

        readinessProbe:
          httpGet:
            path: /health
            port: 6379
          failureThreshold: 1
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 6379
          failureThreshold: 1
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: backend
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    
