aapiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongob://mongodb:27017/catalogue" 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: backend

  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: ramapandu123/catalogue:v1
        imagepullpolicy: always
        envFrom:
        - cinfigMapRef:
            name: catalogue
        ports:
        - name: liveness-port
          containerPort: 8080

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
