apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: catalogue
    tier: backend

spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db

  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: ramapandu123/mongodb:v1
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 27017   # service port
      targetPort: 27017   # container port



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongodb
#   namespace: roboshop
#   labels:
#     project: roboshop
#     component: mongodb
#     tier: db
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       project: roboshop
#       component: mongodb
#       tier: db
#   template:
#     metadata:
#       labels:
#         project: roboshop
#         component: mongodb
#         tier: db
#     spec:
#       containers:
#       - name: mongodb
#         image: ramapandu123/mongodb:v1
#         ports:
#         - containerPort: 27017
# apiVersion: v1
# kind: service
# metadata:
#   name: mongodb
#   namespace: roboshop
# spec:
#   selecter:
#     project: roboshop
#     component: mongodb
#     tier: db
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetport: 27017